[env:esp12e]
platform = espressif8266
board = esp12e
framework = arduino
upload_speed = 921600
board_build.flash_mode = dout
board_build.f_cpu = 100000000L
monitor_filters = time, send_on_enter
build_src_filter = +<esp.cpp>


[env:nanoatmega328]
platform = atmelavr
board = nanoatmega328new
framework = arduino
upload_protocol = arduino
build_src_filter = +<nano.cpp>
monitor_filters = time, send_on_enter



